package ie.setu.pupplan.Activities

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.google.android.material.snackbar.Snackbar
import ie.setu.pupplan.Models.LocationModel
import ie.setu.pupplan.databinding.ActivityPupplanBinding
import ie.setu.pupplan.main.MainApp
import timber.log.Timber.i

class LocationActivity : AppCompatActivity() {

//    View Binding initiated to link module to layout file activity_pupplan.xml
//    ActivityPupplanBinding is autogenerated class that just needs to be imported, as binding is switched on in build.gradle
    private lateinit var binding: ActivityPupplanBinding

//    bring in data model
    var location = LocationModel()
//reference to the main app object (lateinit overrules null safety checks)
    lateinit var app : MainApp

//    main function
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
//     inflater takes an XML file as input and builds the View objects from it
        binding = ActivityPupplanBinding.inflate(layoutInflater)
        setContentView(binding.root)
//initialising the main class
        app = application as MainApp
        i("Pupplan Activity started...")

        binding.btnAdd.setOnClickListener(){
            location.title = binding.locationTitle.text.toString()
            location.description = binding.locationDescription.text.toString()
            if (location.title.isNotEmpty()) {
                app.locations.add(location.copy())
//              logging from Timber in mainapp
                i("add Button Pressed: $location")
//                iterates through the indices of the locations list and logs a message for each location, including its index within the list. It will print the location and its corresponding index.
                for (i in app.locations.indices)
                { i("Location[$i]:${this.app.locations[i]}") }
            }
            else {
                Snackbar
                    .make(it, "Please Enter a title", Snackbar.LENGTH_LONG)
                    .show()
            }
        }
    }
}